# Generated by Django 4.0.3 on 2022-03-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark an item deleted without actually deleting it from database. I.e, soft deletion.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion date and time.', null=True)),
                ('created_by_id', models.IntegerField(help_text='User ID from the Authentication system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The creation time, always in Asia/Kolkata timezone.')),
                ('updated_by_id', models.IntegerField(help_text='User ID from the Authentication system', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last update time, always in Asia/Kolkata timezone.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark an item deleted without actually deleting it from database. I.e, soft deletion.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion date and time.', null=True)),
                ('created_by_id', models.IntegerField(help_text='User ID from the Authentication system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The creation time, always in Asia/Kolkata timezone.')),
                ('updated_by_id', models.IntegerField(help_text='User ID from the Authentication system', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last update time, always in Asia/Kolkata timezone.')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_fabric', models.PositiveSmallIntegerField(choices=[(1, 'Nylon'), (2, 'Cotton'), (3, 'Polyester')])),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Blue'), (2, 'Black'), (3, 'Green'), (4, 'White')])),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.ManyToManyField(related_name='products', to='products.productsize')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
